buildCommand: "npm install && npm run build"
startCommand: "npm start"
healthCheckPath: "/"
env:
  - key: PORT
    value: "10000"
    readOnly: true
  - key: MAIL_TO
    value: "Alejandromg94@outlook.com"
  - key: SMTP_HOST
    value: "smtp.office365.com"
  - key: SMTP_PORT
    value: "587"
  - key: SMTP_SECURE
    value: "false"
  - key: SMTP_USER
    value: "Alejandromg94@outlook.com"
  - key: SMTP_PASS
    value: "PON_AQUI_EL_PASSWORD_DE_APLICACION_EN_EL_DASHBOARD_DE_RENDER"
  - key: MAIL_FROM
    value: "Alejandromg94@outlook.com"
